### ISSUE TITLE
Frequent Failures

### ISSUE THREAD

**Issue by GabrielSieben** [kaltura/adobe-connect-to-mkv-to-kaltura#15]
I am frequently having failures because of this:
```

E
===============================================================================
Error: test_vconn1(Vconn1):
  NameError: undefined local variable or method `log' for #<Vconn1:0x0000560d807d1980>
  Did you mean?  load
/root/kaltura-adobe-connect/adobe-connect-to-mkv-to-kaltura/ac_new.rb:109:in `test_vconn1'
     106:         return false
     107:       end
     108:     else
  => 109:       log.error('Failed to get duration from audio track or XML metadata :(')
     110:       return false
     111:     end
     112:
===============================================================================
E
===============================================================================
```

I don't know what else to say. Help.

**Comment by kaltura-hooks** [comment]
Hi @gjsman,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi @gjsman,

See https://github.com/kaltura/adobe-connect-to-mkv-to-kaltura/blob/master/ac_new.rb#L98
This will happen if the recording has no audio track at all. Is that the case?
If so, you'll need to revise the code to handle such recordings. At the moment, the code assumes that an audio track is present, as well as a video one.

**Comment by GabrielSieben** [comment]
I got a little further today... Apparently, if the Adobe Connect recording (for whatever reason) doesn't finish downloading or gets cancelled, the next time I run the command it will simply reuse the half-downloaded files, which predictably fails...

I am having issues other than this one soon. I will post the next time they happen (which shouldn't be too long).

**Comment by jessp01** [comment]
Okay, so can we close this one?

**Comment by GabrielSieben** [comment]
For now, yes. My bad.
