### ISSUE TITLE
Overlapping Audio

### ISSUE THREAD

**Issue by GabrielSieben** [kaltura/adobe-connect-to-mkv-to-kaltura#16]
Hello,

I set up a server and (besides #15 ), I'm having another problem: I set it to record 4 meetings at once, and the audio for all 4 meetings appeared in all 4 recordings - a combined mess.

I have no idea how to fix this. I have the latest version of pulse audio, on Ubuntu 18.04, if that matters.

**Comment by kaltura-hooks** [comment]
Hi @gjsman,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by GabrielSieben** [comment]
Also, the Audio appears to just "cut off" a few minutes into the recordings.

Almost like, it goes like this:

Video #1 with Audio #1: Plays (normal) for about 4 minutes
Video #2 starts with Audio #2, Hijacks Audio #1 and now has both Audio #1 and #2 playing, for about 4 minutes
Video #3 starts with Audio #3, Hijacks Audio #1 and #2 and now has Audio #1 and #2 and #3 playing, for about 4 minutes
Video #4 starts with Audio #4, Hijacks all audio before it, disastrous

**Comment by GabrielSieben** [comment]
Yep, this is what is happening. I can submit links to those videos to see for yourself (privately) if you want.

**Comment by jessp01** [comment]
Hello @gjsman,

On one occasion, we observed a similar behaviour with Ubuntu 18.04. However, since the machines we ran this code on were all running Ubuntu 16.04, where the issue did not reproduce, we weren't very motivated to investigate further.
This code is licensed under AGPLv3 and we welcome contributions so should you decide to investigate and find a solution for Ubuntu 18.04, please feel free to submit a pull request.
Otherwise, I suggest you try running the code on Ubuntu 16.04 and let us know as to the results.

Cheers,

**Comment by GabrielSieben** [comment]
No more problems with audio mashup on 16.04, but instead having a new issue: #17 .
