### ISSUE TITLE
Video stops recording at wrong times

### ISSUE THREAD

**Issue by GabrielSieben** [kaltura/adobe-connect-to-mkv-to-kaltura#17]
I'm having a problem where my videos incorrectly identify when to end. This is on Ubuntu 16.04.
I recorded 2 videos. One ended only 22 minutes into the recording, whereas the other went 18 minutes past the recording ending before suddenly stopping. Curiously, I redid the first video twice afterwards, and all three times it consistently ended at 22 minutes in.

**Comment by kaltura-hooks** [comment]
Hi @gjsman,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by GabrielSieben** [comment]
I've dug into the code a little bit (I don't know ruby, but can still at least look), and I'm wondering if perhaps this was caused by downloading the recording incompletely the first time, getting only part of the audio, and because ffmpeg's recording length is determined by the length of the audio, ...

I'm going to delete /tmp and retry. No idea about the 18+minutes longer one though.

**Comment by GabrielSieben** [comment]
Deleting /tmp and restarting did not fix this problem.

It consistently ends on this one recording at 24:16 or 24:17. Nothing visible in the video. 😕

**Comment by GabrielSieben** [comment]
For what it's worth, the MP3 is also about this long. My theory is that something in my setup is either causing it to not create the correct MP3 sizes, or Adobe Connect is doing something fishy over on their end...

**Comment by jessp01** [comment]
Hello @gstman,

As you can see here:
https://github.com/kaltura/adobe-connect-to-mkv-to-kaltura/blob/master/ac_new.rb#L170

We let the `ffmpeg` CLI binary capture the X11 display for the value the `duration` var contains (passing `-t  duration.to_s` as an argument).
The initial value for `duration` is taken from the `DURATION` ENV var (exported in ac_wrapper.sh, after parsing the input CSV). As you can see in the code block I referenced in the original issue you opened (https://github.com/kaltura/adobe-connect-to-mkv-to-kaltura/blob/master/ac_new.rb#L98-L111), if that value is bigger than zero, we use it, since we observed that the AC API often returned incorrect duration values or no values at all for many sessions, if the value is not bigger than zero, we attempt to determine the session's length by analysing the audio track instead.
Since you say the length of the audio track is the same as that of the recording produced by running this code, the end result is not surprising.

You can manually adjust the value in the input CSV for the entries, however.

**Comment by GabrielSieben** [comment]
Okay, that make sense. But why is the audio track cut short?

**Comment by GabrielSieben** [comment]
Okay... well, I'm doing some research, and it appears that meetings were sometimes began recording when the instructor wasn't present (for about 10 minutes or so ahead of time), and then edited to hide that first 10 minutes.

Well, Adobe Connect edits the video portion, but not the audio - so there is a 10 minute or so "no sound" portion at the beginning of each audio track. FFMpeg then records, as a result, 10 minutes past the video ending.

So, that's the long videos explained. The short one is still unexplained.
