### ISSUE TITLE
Helpful program I wrote for this system

### ISSUE THREAD

**Issue by GabrielSieben** [kaltura/adobe-connect-to-mkv-to-kaltura#18]
Hello!

I am using this Kaltura conversion program to help a company move hundreds of recordings to MP4 and reduce the need for the real-time conversion feature that Adobe Connect provides (which is a massive time waste). The Kaltura conversion program works generally well, but finding SCOs for specific categories can take a very long time. To speed this up, I wrote a program which helps me find piles of SCOs for each category in only a few clicks. I licensed it as AGPLv3, just like this Kaltura converter.

If there's any way to promote this wider among users of this conversion program, that would be great. I just hope it's useful for other people and not just myself.

https://github.com/gjsman/Adobe-Connect-SCO-Viewer

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/29414519/67806315-9a0f2900-fa60-11e9-8f5d-b5189df32115.png">

**Comment by jessp01** [comment]
Hello @gjsman,

I'm glad to hear that you found this helpful and that you've contributed something that may help others with this task:)
I suggest you use `$_SERVER['REQUEST_SCHEME']` rather than the hard coded 'http' references. For example here: https://github.com/gjsman/Adobe-Connect-SCO-Viewer/blob/master/index.php#L23

Cheers,

**Comment by jessp01** [comment]
Closing this since the repo referenced is no longer accessible. If you have moved it and wish to reference it, I'd gladly accept a contribution to the README file.

Thanks,
